export { default as Home } from './Home'
export { default as Login } from './auth/Login'
export { default as Register } from './auth/Register'
export { default as NotFound } from './NotFound'
export { default as User } from './User'
export { default as ProductDetail } from './ProductDetail'
export { default as Cart } from './Cart'
